name: "terraform-deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  TerraformDeploy:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set AWS access key ID from secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set AWS secret access key from secrets

    steps:
      - uses: actions/checkout@v2  # Checkout the repository to the GitHub Actions runner

      - name: Setup Terraform  # Use the 'hashicorp/setup-terraform' action to set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init  # Initialize Terraform and format the configuration
        id: init
        run: |
          terraform fmt  # Format the Terraform configuration
          terraform init -upgrade  # Initialize Terraform and upgrade modules if available

      - name: Terraform Plan  # Generate Terraform execution plan
        id: plan
        run: terraform plan -input=false -out=tfplan  # Generate a plan and save it as 'tfplan' file

      - name: Terraform Apply  # Apply the Terraform configuration
        run: terraform apply -auto-approve -replace=tfplan        # Apply Terraform changes using the generated plan
        

